#!/bin/sh
# ======================================
# Test command
# ======================================
echo '   999  example1           available    [ =1.0 ]'
echo '   999  example2           enabled      [ =1.0 ]'
