version: 2

jobs:
  doclint:
    docker:
      - image: lexauw/ansible-alpine
        environment:
          ANSIBLE_LIBRARY: './src'
    steps:
      - run: ansible-doc -t module amazon_linux_extras
  test:
    docker:
      - image: amazonlinux:2
    steps:
      - run: amazon-linux-extras install -y ansible2

workflows:
  version: 2
  test:
    jobs:
      - doclint
      - test
