version: 2

jobs:
  doclint:
    docker:
      - image: lexauw/ansible-alpine
        environment:
          ANSIBLE_LIBRARY: './src'
    steps:
      - run: ansible-doc -t module amazon_linux_extras
  flake8:
    docker:
      - image: circleci/python:2.7-node
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run: |
          pip install --user pipenv
          pipenv install --dev
      - run: pipenv run flake8
  pytest:
    docker:
      - image: circleci/python:2.7-node
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run: |
          pip install --user pipenv
          pipenv install --dev
      - run: pipenv run pytest
  pytest-python3:
    docker:
      - image: circleci/python:3.7-node
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run: |
          pip install --user pipenv
          pipenv install --dev
      - run: pipenv run pytest
  playbook:
    docker:
      - image: amazonlinux:2
    steps:
      - run: amazon-linux-extras install -y ansible2
      - checkout
      - run: |
          mkdir -p ~/.ansible/plugins/modules/
          cp amzn2extra.py ~/.ansible/plugins/modules/
          ansible-playbook -i demo/inventory.yml demo/run.yml
      - run: php -v
workflows:
  version: 2
  test:
    jobs:
      - flake8
      - doclint
      - pytest
      - pytest-python3
      - playbook
